#################### Test ##############################
GET http://localhost:9000/health
Content-Type: application/json

#################### User ##############################
###
POST http://localhost:9000/auth/signin
Content-Type: application/json

{
    "email": "embarkemail@gmail.com",
    "password": "Emp!12345",
    "userType": "student"
}

###
POST http://localhost:9000/auth/signup
Content-Type: application/json

{
    "firstName": "helloa",
    "lastName": "bruin",
    "email": "bruin151!!@email.com",
    "password": "12345qQ!",
    "userType": "student"
}

###
POST http://localhost:9000/auth/google
Content-Type: application/json

{
    "type": "signin",
    "user": "student"
}

###
POST http://localhost:9000/auth/linkedin
Content-Type: application/json

{
    "type": "signin",
    "user": "student"
}


############ Authorization Needed #################################
############ Posts ################################################
### Fixing in the backend
GET http://localhost:9000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzdjN2YzYTk4YjdjMDAxZmJlZmNkOCIsIm5hbWUiOiJoZWxsb2EiLCJlbWFpbCI6ImJydWluMTUxISFAZW1haWwuY29tIiwiaWF0IjoxNjE4NDYyNzA3LCJleHAiOjE2MjcxMDI3MDd9.sJLdWdm3mLlGyGvs5xGKz8_JLGIT79G-zfPUaCy-57Q
Content-Type: application/json

### 
GET http://localhost:9000/posts?limit=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzdjN2YzYTk4YjdjMDAxZmJlZmNkOCIsIm5hbWUiOiJoZWxsb2EiLCJlbWFpbCI6ImJydWluMTUxISFAZW1haWwuY29tIiwiaWF0IjoxNjE4NDYyNzA3LCJleHAiOjE2MjcxMDI3MDd9.sJLdWdm3mLlGyGvs5xGKz8_JLGIT79G-zfPUaCy-57Q
Content-Type: application/json


###
POST http://localhost:9000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMzJlMDlhOGFlYmQ0MjI2ODkxMmZmYiIsIm5hbWUiOiJlbWJhcmsiLCJlbWFpbCI6ImVtYmFya2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTYxMzk1MDg4NiwiZXhwIjoxNjIyNTkwODg2fQ.-TZJmcfn1tro8kvAO_ThSAmhyDzhwuSicZlPk-i7Drc
Content-Type: application/json

{
    "title": "test title",
    "body": "test frontend",
    "accountType": "student"
}

###
POST http://localhost:9000/posts/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMzJlMDlhOGFlYmQ0MjI2ODkxMmZmYiIsIm5hbWUiOiJlbWJhcmsiLCJlbWFpbCI6ImVtYmFya2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTYxMzk1MDg4NiwiZXhwIjoxNjIyNTkwODg2fQ.-TZJmcfn1tro8kvAO_ThSAmhyDzhwuSicZlPk-i7Drc
Content-Type: application/json

{
    "authorEmail": "embarkemail@gmail.com",
    "post_id": "6046b8a11a39630050538c35"
}

###
GET http://localhost:9000/posts/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzdjN2YzYTk4YjdjMDAxZmJlZmNkOCIsIm5hbWUiOiJoZWxsb2EiLCJlbWFpbCI6ImJydWluMTUxISFAZW1haWwuY29tIiwiaWF0IjoxNjE4NDYyNzA3LCJleHAiOjE2MjcxMDI3MDd9.sJLdWdm3mLlGyGvs5xGKz8_JLGIT79G-zfPUaCy-57Q
Content-Type: application/json


###
POST http://localhost:9000/posts/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzdjN2YzYTk4YjdjMDAxZmJlZmNkOCIsIm5hbWUiOiJoZWxsb2EiLCJlbWFpbCI6ImJydWluMTUxISFAZW1haWwuY29tIiwiaWF0IjoxNjE4NDYyNzA3LCJleHAiOjE2MjcxMDI3MDd9.sJLdWdm3mLlGyGvs5xGKz8_JLGIT79G-zfPUaCy-57Q
Content-Type: application/json

{
    "authorEmail": "bruin151!!@email.com",
    "post_id": "6012dce8eb36de011c96c7e4",
    "comment": "nothing"
}


###
POST http://localhost:9000/posts/likes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMzJlMDlhOGFlYmQ0MjI2ODkxMmZmYiIsIm5hbWUiOiJlbWJhcmsiLCJlbWFpbCI6ImVtYmFya2VtYWlsQGdtYWlsLmNvbSIsImlhdCI6MTYxMzk1MDg4NiwiZXhwIjoxNjIyNTkwODg2fQ.-TZJmcfn1tro8kvAO_ThSAmhyDzhwuSicZlPk-i7Drc
Content-Type: application/json

{
    "authorEmail": "embarkemail@gmail.com",
    "post_id": "6012dce8eb36de011c96c7e4"
}

############ Users ################################################
###
GET http://localhost:9000/student/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmE0YmJhY2UwMjU1MDAyZGQxMWI0OCIsIm5hbWUiOiJvdXRkYXRlZCBBUEkiLCJlbWFpbCI6InNoYWl2aXMxODIzQGdtYWlsLmNvbSIsImlhdCI6MTYxNzU3ODkzOCwiZXhwIjoxNjI2MjE4OTM4fQ.m4j6dFSyYFiOeFWUsnFVvbUIjKjpMlfEz5__8I6lIg8
Content-Type: application/json
###
POST http://localhost:9000/student/profile 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMTdjMjUzOTA3NzQ4MzJmMjEzYjNmYyIsIm5hbWUiOiJqb2huIHNtYWxsYmVyZzEiLCJlbWFpbCI6ImpvaG4xQGVtYWlsLmNvbSIsImlhdCI6MTYxMjIwNDA4NiwiZXhwIjoxNjIwODQ0MDg2fQ.kT3fUNe433ue1SG89ngnRjk5CErTMBZsH4X3xAeG_Pk
Content-Type: application/json

{
    "year": "2023",
    "major": "Computer Science",
    "tags": ["Developer", "Musician"],
    "linkedIn": "johnsmallberg"
}
###
############# Clubs #################################################
GET http://localhost:9000/club/discover
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNmE0YmJhY2UwMjU1MDAyZGQxMWI0OCIsIm5hbWUiOiJvdXRkYXRlZCBBUEkiLCJlbWFpbCI6InNoYWl2aXMxODIzQGdtYWlsLmNvbSIsImlhdCI6MTYxNzU3ODkzOCwiZXhwIjoxNjI2MjE4OTM4fQ.m4j6dFSyYFiOeFWUsnFVvbUIjKjpMlfEz5__8I6lIg8