import { Select, makeStyles } from "@material-ui/core";
import styled from "styled-components";

export const IndustryFilters = [
  "Medical",
  "Dentistry",
  "Pharmacy",
  "Nursing",
  "Health",
  "Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Tech",
  "Product",
  "Computer Science",
  "Software Development",
  "Product Management",
  "Product Design",
  "UX/UI Design",
  "Design",
  "Consulting",
  "Strategy Operations",
  "Investment Banking",
  "Marketing",
  "Real Estate",
  "Accounting",
  "Corporate Finance",
  "Financial Technology",
  "Commercial Banking",
  "Financial Planning",
  "Private Equity/Venture Capital",
  "Insurance",
  "Hedge Funds",
];
