export const IndustryFilters = [
    "medical",
    "dentistry",
    "pharmacy",
    "nursing",
    "health",
    "engineering",
    "electrical engineering",
    "mechanical engineering",
    "tech",
    "product",
    "computer science",
    "software development",
    "product management",
    "product design",
    "UX/UI design",
    "design",
    "consulting",
    "strategy operations",
    "investment banking",
    "marketing",
    "real estate",
    "accounting",
    "corporate finance",
    "financial technology",
    "commercial banking",
    "financial planning",
    "Private Equity/venture capital",
    "insurance",
    "hedge funds",
    ]